languages:
#  python:
#    versions:
#      - 3.8
   #   - '3.10'
   #   - 3.11
   #   - 3.12
       - 3.12.10
   #   - 3.13
  java:
    versions:
      - 8
#      - 11
#      - 17
#  node:
#    versions:
#      - 16
   #   - 18
   #   - 20
   #   - 22
