# Use a base image
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Accept Node.js version as an argument
ARG NODE_VERSION

# Install Node.js and npm
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Verify installation
RUN node -v && npm -v

# Set default entrypoint
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["node -v"]
