name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ env.MATRIX }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read YAML Files and Generate Matrix
        run: python .github/scripts/generate_matrix.py

  build-docker:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          DOCKER_TAG="${{ matrix.language }}:${{ matrix.version }}"
          echo "Building Image: $DOCKER_TAG"
          docker build --build-arg BASE_IMAGE=${{ matrix.base_image }} --build-arg PACKAGES="${{ matrix.packages }}" -t myrepo/$DOCKER_TAG .
          
      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push myrepo/${{ matrix.language }}:${{ matrix.version }}
