name: Build Docker Images

on:
  push:
    branches:
      - new_images

jobs:
  build-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ env.MATRIX }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read YAML Files and Generate Matrix
        run: python .github/scripts/generate_matrix.py



  build-docker:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Dockerfile from Template
        run: |
          cat Dockerfile.template | sed "s|{{BASE_IMAGE}}|${{ matrix.base_image }}|g" | sed "s|{{PACKAGES}}|${{ matrix.packages }}|g" > Dockerfile

      - name: Build Docker Image
        run: |
          DOCKER_TAG="${{ matrix.language }}:${{ matrix.version }}"
          echo "Building Image: $DOCKER_TAG"
          docker build -t myrepo/$DOCKER_TAG .
          
      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push myrepo/${{ matrix.language }}:${{ matrix.version }}

